version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ghcr.io/nathanrish/video-chunker:v1.1.0
    ports:
      - "5004:5004"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./output:/app/output
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  output:
    driver: local
